services:
    mongodb_container:
        image: mongo:latest
        command: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/mongodb-keyfile"]
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - ${MONGO_PORT:-27017}:27017
        volumes:
            - mongodb_data_container:/data/db
            - ./mongodb-keyfile:/data/mongodb-keyfile:ro
        healthcheck:
            test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb_container:27017'}]}) }" | mongosh --username root --password rootpassword --authenticationDatabase admin
            interval: 5s
            timeout: 30s
            start_period: 0s
            start_interval: 1s
            retries: 30
    localstack:
        image: localstack/localstack:3.4.0
        environment:
            - SERVICES=sqs,sns
            - AWS_DEFAULT_REGION=us-east-1
            - EDGE_PORT=4566
            - SQS_ENDPOINT_STRATEGY=off
        ports:
            - '4566-4597:4566-4597'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
    mongodb_data_container:
